name: Docker

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Push to GHCR
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: phnx47/harvest-report
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PKG_PAT }}
          registry: ghcr.io
