name: Linters
on: [pull_request]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  commitlint:
    name: commitlint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Issue: https://github.com/conventional-changelog/commitlint/issues/3256
      - name: Fix conventional-changelog/commitlint#3256 issue
        run: rm tsconfig.json
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5
