name: Report

on:
  schedule:
    - cron: "0 9 * * 5"
  workflow_dispatch:

jobs:
  send-report:
    name: Send Report
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Run
        run: npm start >> report.txt

      - name: Read report.txt
        id: report
        uses: juliangruber/read-file-action@v1
        with:
          trim: true
          path: ./report.txt

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER_ADDRESS }}
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Harvest-Report (${{ github.run_number }})
          body: |
            Generated via GitHub Actions [1]

            ${{ steps.report.outputs.content }}

            [1] https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
