name: Report

on:
  schedule:
    - cron: "0 9 * * 5"
  workflow_dispatch:

jobs:
  send-report:
    name: Send Report
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i --omit=dev

      - name: Generate Report
        run: ./cli.js -m
        env:
          HARVEST_ACCESS_TOKEN: ${{ secrets.HARVEST_ACCESS_TOKEN }}
          HARVEST_ACCOUNT_ID: ${{ secrets.HARVEST_ACCOUNT_ID }}
          HARVEST_CLIENT_ID: ${{ secrets.HARVEST_CLIENT_ID }}
          MAIL_SERVER_ADDRESS: ${{ secrets.MAIL_SERVER_ADDRESS }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
